### ISSUE TITLE
Installation on Python 3.4 and virtualenv fails

### ISSUE THREAD

**Issue by krother** [alexsavio/pydger#10]
When installing via pip or setup.py, I get an error message:

    TypeError: parse_requirements() missing 1 required keyword argument: 'session'

**Comment by alexsavio** [comment]
Hi @krother,

I am sorry, I should've removed pydger a long time ago. Please use pythonsansebastian/docstamp instead. Let me know how it works for you.

**Comment by krother** [comment]
*g* kind of answers the e-mail I jut sent to you.

**Comment by alexsavio** [comment]
I got no email.
